name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: AliMousaviSoft
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: America/New_York

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_topics: yes
          plugin_topics_limit: 6

          plugin_stars: yes
          plugin_stars_limit: 6

          plugin_followup: yes

          plugin_repositories: yes
          plugin_repositories_featured: AliMousaviSoft/Hunt-kit,AliMousaviSoft/pentest-guide,AliMousaviSoft/sondra,AliMousaviSoft/subjackal

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          plugin_lines: yes

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
